#Basic EC2 instance Creation with security groups and public IPv4 address
Resources:
  BasicEc2Instance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-05c13eab67c5d8861
      InstanceType: t3.micro
      SecurityGroups:
        - !Ref SecurityGroupOne
        - !Ref SecurityGroupTwo

  # Associating Elastic IP address for the instance, 
  # A public IPv4 address reachable from the internet
  BasicEIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref BasicEc2Instance

  # Security Group Essentials for TCP ssh access
  SecurityGroupOne:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enables access via SSH
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        FromPort: 22
        IpProtocol: tcp
        ToPort: 22

  # Security Group Essentials for HTTP access
  SecurityGroupTwo:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enables access to http protocol packets
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 192.168.1.1/32

