#Basic EC2 instance Creation with Image ID and Instance Type

Resources:
  BasicEc2Instance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-05c13eab67c5d8861
      InstanceType: t3.micro
