Parameters:
  DBUsername:
    Type: "String" 
  DBPassword:
    Type: "String" 

Resources:

  DbSubnetA:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: 'eu-west-1a'
      VpcId: !ImportValue VpcInstance
      CidrBlock: 10.155.0.96/28

  DbSubnetB:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: 'eu-west-1b'
      VpcId: !ImportValue VpcInstance
      CidrBlock: 10.155.0.128/28

  DbSubnetGroup:
    Type: "AWS::RDS::DBSubnetGroup"
    Properties:
      DBSubnetGroupName: RdbSubnetGroup
      DBSubnetGroupDescription: "Subnet Group"
      SubnetIds:
      - !Ref DbSubnetA
      - !Ref DbSubnetB
  
  DbInstanceSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupName: "Security Group"
      GroupDescription: "RDS traffic"
      VpcId: !ImportValue VpcInstance

  DbInstanceSecurityGroupIngress:
    Type: "AWS::EC2::SecurityGroupIngress"
    DependsOn: DbInstanceSecurityGroup
    Properties:
      GroupId: !Ref DbInstanceSecurityGroup
      IpProtocol: tcp
      FromPort: 0
      ToPort: 65535
      SourceSecurityGroupId: !Ref DbInstanceSecurityGroup
  
  DSSGIngressRule:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      FromPort: "3306"
      ToPort: "3306"
      GroupId: !Ref DbInstanceSecurityGroup
      IpProtocol: tcp
      SourceSecurityGroupId: !Ref DbInstanceSecurityGroup

  DataSourceSubtNetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Created by CF
      SubnetIds:
              - !Ref DbSubnetA
              - !Ref DbSubnetB
  DataSource:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: '5'
      DBInstanceClass: db.t2.micro
      DBName: PhpDatabase
      DBSubnetGroupName: !Ref DataSourceSubtNetGroup
      Engine: mysql
      EngineVersion: 8.0.33
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      PubliclyAccessible: false
      MultiAZ: true
      VPCSecurityGroups:
              - !Ref DbInstanceSecurityGroup